Add confirmation to delete notes on the Location page and Crash page
cityofaustin/atd-vz-data pull request #1339
Opened 2024-01-05 21:12 UTC by mddilley

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/14771

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-01-05 23:11 UTC, patrickm02L approved these changes
I went back and forth thinking about whether the CTA should say "Delete" or "Confirm" I think confirm makes sense to keep it as "Confirm" here because you're asking them if they're sure they want to delete. 

But I think we should change the `modalHeader` to Delete Confirmation versus Delete Note.

Otherwise, everything's go to go!
<img width="705" alt="Screen Shot 2024-01-05 at 5 02 23 PM" src="https://github.com/cityofaustin/atd-vz-data/assets/5566727/5a7b3161-2642-493e-80d2-5797916f5728">

2024-01-08 17:44 UTC, mddilley commented
@patrickm02L Thanks! I just pushed the update to the header text.

2024-01-10 14:33 UTC, frankhereford requested changes
Mike, thanks for adding this helpful feature. I think the modal looks great, and it's cool you were able to reuse one we had in the code base.

I was able to get it to do some unexpected behavior, which you can see here:

https://github.com/cityofaustin/atd-vz-data/assets/3653206/d10e404b-b15f-4b60-b9b7-a8f74ef7d578

I think you might need to do something like set the record ID in a state variable at the time toggleModal is called and use that later if/when handleDeleteClick is invoked. I think right now handleDeleteClick is going to operate on the last row that was rendered, which ends up being the last row on the table. Take me with a grain of salt of course!

2024-01-10 16:05 UTC, mddilley commented
@frankhereford Thanks for catching that! I was just able to reproduce that bug locally, and I'll take a look at it today.

2024-01-10 17:48 UTC, mddilley commented on atd-vze/src/containers/DefaultLayout/DefaultHeader.js
> +                <i className="fa fa-briefcase" /> CR3 code sheet&nbsp;&nbsp; <i className="fa fa-external-link" />
Fixes a console warning

2024-01-10 17:51 UTC, mddilley commented
@frankhereford I just pushed a fix, and I think that should do the trick. The bug came down to me overlooking that every modal rendered was sharing the same `showModal` state. Thanks again!

2024-01-10 17:53 UTC, frankhereford approved these changes
Thanks Mike!! 🚢 🚢 🚢

2024-01-10 18:04 UTC, chiaberry approved these changes
tested and ✔️ 

A future enhancement could be to include the text of the note the person is deleting, or somehow denote what specific note a person is deleting. but thats for the future!

2024-01-10 18:08 UTC, mddilley commented
@chiaberry I like that idea a lot! It would be a small change and small effort to fit that in this PR. What you think @patrickm02L? Also happy to make a spin-off issue

2024-01-10 18:12 UTC, patrickm02L commented
> @chiaberry I like that idea a lot! It would be a small change and small effort to fit that in this PR. What you think @patrickm02L? Also happy to make a spin-off issue

Let's include it!

2024-01-10 19:10 UTC, mddilley commented
Alright, I updated the modal to show text of the note being deleted. To test:
1. add several notes and one with really long text (my go-to is [pizza ipsum](https://pizzaipsum.com/?paras=5&type=all-custom&start-with-lorem=1))
2. try deleting any of them and see that the note or truncated note is shown in the modal

2024-01-11 14:51 UTC, patrickm02L approved these changes
Thanks for making the addition of adding the text being deleted in the confirmation pop-up, and making sure numbers show up. Send it 🍕 

<img width="603" alt="Screen Shot 2024-01-11 at 8 48 07 AM" src="https://github.com/cityofaustin/atd-vz-data/assets/5566727/265a51bb-8736-4d20-beb7-0a4d9c9f6df0">

<img width="557" alt="Screen Shot 2024-01-11 at 8 49 42 AM" src="https://github.com/cityofaustin/atd-vz-data/assets/5566727/4f08a9a6-3af2-4e55-9821-7b9a009b1fef">

2024-01-11 15:44 UTC, merged