[Enhancement] Increase change log modal width and wrap text
cityofaustin/atd-vz-data pull request #1403
Opened 2024-03-18 22:19 UTC by mddilley

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/15894

This makes a few updates to the change log modal to prevent horizontal scrolling from happening on screens with plenty of real estate.

## Testing
**URL to test:** 
TBD

**Steps to test:**
1. Find a crash with change log entries like:
2. Go to the bottom of the page and click **Compare** on one of the change log rows
3. When the modal opens, notice that it takes up the majority of the width available in your browser window
4. Also, notice as you decrease the browser width, the text in the current and previous columns wrap and break to prevent side-scrolling early on. `cr3_file_metadata` is a good indicator of this behavior.

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-03-18 22:20 UTC, mddilley commented on atd-vze/src/views/Crashes/CrashChangeLog.js
> +    let modalItems = diff.map((item, i) => {
this fixes a key warning. Index is okay here since the order of these items won't change after initial render.

2024-03-18 22:21 UTC, mddilley commented on atd-vze/src/views/Crashes/CrashChangeLog.js
> +            <Badge color="primary" className="text-wrap text-break">
new classes here to handle the word wrap

2024-03-18 22:22 UTC, mddilley commented on atd-vze/src/views/Crashes/CrashChangeLog.js
> +        <Modal isOpen={this.state.modal} className="mw-100 mx-5">
There is a `modal-xl` class in Bootstrap 4 but it wasn't super wide so I made this take up the whole width and added some margin prevent it from rendering all the way to the edge.

2024-03-18 22:22 UTC, mddilley commented on atd-vze/src/views/Crashes/CrashChangeLog.js
> +                <tr key={`changelog-${record.change_log_id}`}>
One more key warning fix

2024-03-19 14:37 UTC, frankhereford approved these changes
Mike, thank you for this. This makes this tool instantly much more useful and easier to use. As it is, this is already a huge improvement and is shippable. 🚢 

I was wondering about what you thought this change, and totally no big if you think it's a bad idea.

You can see in this screenshot, that the horizontal scrollbar is still there, however, your changes make it largely moot, since it seems to be able to show >95% of the width no matter how I resize the viewport. 

![has_scroll_bar](https://github.com/cityofaustin/atd-vz-data/assets/3653206/7e94dac4-1dbc-410e-8e7e-266d13dc367f)

Do you think it would be possible to change the `overflow-x` value in some version of this deeply specified tag:
```
body > div:nth-child(12) > div > div.modal.fade.show > div > div > div.modal-body > section > div
```
Maybe something like this as the selector? I don't have a copy of the DB replicated with changelog data handy; I have not tested, so take me with a grain of salt!
```
div.modal.fade.show > div.modal-body
```
Here's maybe a better demonstration of what I'm trying to convey:


https://github.com/cityofaustin/atd-vz-data/assets/3653206/563e82fd-194d-41e5-90d8-d65abfcf12e8

Please let me know if I can help explain this better; I feel like I've done a pretty lackluster job here. I also know this is a style set deep in bootstrap on a tag deep in a component we didn't write, so I totally understand if this is more trouble than it's worth.

2024-03-19 15:03 UTC, chiaberry approved these changes

2024-03-19 15:06 UTC, chiaberry commented
This is such an improvement over what exists now

@frankhereford is there a place in vze where you can override styles? or are you suggesting to add a class to that nested div? I cannot remember how the classes work there, versus how they work in material ui. 

fwiw, I think the scrollbar is fine, even if it is vestigal

2024-03-19 17:59 UTC, frankhereford commented
@chiaberry wrote:

> @frankhereford is there a place in vze where you can override styles? or are you suggesting to add a class to that nested div? I cannot remember how the classes work there, versus how they work in material ui.

Great question Chia, I had to look into it myself to figure out a way. I am suggesting a new class to target the div that contains the table of changed fields, yea. Here's what I came up with when looking at how it might be doable. I'm not trying to say this is the best way, but it's a way that seems pretty OK -- what do you think?

https://github.com/cityofaustin/atd-vz-data/compare/md-15894-change-log-modal..apply-custom-css

2024-03-19 18:21 UTC, mddilley commented
@frankhereford @chiaberry just catching up here. thanks for the reviews, and thanks Frank for catching the sneaky scrollbar 🙏 I'm going to push an update that will have a similar effect to your example, Frank. 

I want to give John a chance to check if this is what he envisioned in the first place too. The static column widths are great for large screens, but I'm thinking that we might want a scrollbar on smaller screen? Not sure.

2024-03-19 18:23 UTC, frankhereford commented on atd-vze/src/views/Crashes/CrashChangeLog.js
> +        <Table responsive className="overflow-hidden">
Such an elegant solution - thanks @mddilley ! 🙌

2024-03-20 16:07 UTC, roseeichelmann approved these changes
Huggeeeee improvement! Thanks mike it looks so much better now! :sparkles:

2024-03-22 14:30 UTC, johnclary requested changes
@mddilley this is a really nice improvement! thanks for cleaning up our code along the way.

i have one bit of scope creep, which is not critical. would you mind adding a close button to the modal header, in addition to the existing button in the footer? now that this modal is scrollable i found that i got a tiny bit lost trying to close it 😅

2024-03-22 18:34 UTC, mddilley commented
@johnclary good catch on the modal! when i compared it to the confirmation modal, we were missing the `toggle` prop in the modal and modal header. This gives us the X icon, closing with the esc key, and clickaway to close. Once the deploy is updated, this is ready for another look. 🙏

2024-03-22 18:53 UTC, johnclary approved these changes
niiiiice. much improved! 🚢 🚢 🚢 🚢 🚢 🚢

2024-03-22 18:55 UTC, mddilley commented
thanks, everybody! merging

2024-03-22 18:56 UTC, merged