Crash details page: crash map
cityofaustin/atd-vz-data pull request #1473
Opened 2024-06-07 19:09 UTC by roseeichelmann

## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/17182

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-06-10 20:54 UTC, roseeichelmann commented on atd-vze/src/views/Crashes/Crash.js
> -  };
this was not actually being used for anything?

2024-06-21 14:03 UTC, johnclary requested changes
this is fantastic! i flagged a few minor things.

2024-06-27 17:17 UTC, roseeichelmann commented
@johnclary ready for re-review! worth checking to make sure none of your change log stuff that got merged into `data-model-v2` was affected but im pretty sure there were no regressions thru my own testing and looking at the code diff in this PR

2024-06-27 20:19 UTC, johnclary commented on atd-vze/package-lock.json
i think this is fine 🤷

2024-06-27 20:21 UTC, johnclary approved these changes
yep—this is ready to merge! thanks @roseeichelmann! 🚢 🚢 🚢 🚢 🚢

2024-06-27 20:24 UTC, roseeichelmann commented on atd-vze/package-lock.json
me too :shrug:

2024-06-27 20:24 UTC, merged