Add total person comp cost to the crash details page
cityofaustin/atd-vz-data pull request #1513
Opened 2024-08-19 20:56 UTC by roseeichelmann

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-08-19 22:59 UTC, roseeichelmann commented on atd-vzd/metadata/databases/default/tables/public_crash_injury_metrics_view.yaml
> +        - est_total_person_comp_cost
just added this and other stuff got rearranged

2024-08-19 22:59 UTC, roseeichelmann commented on atd-vzd/metadata/databases/default/tables/tables.yaml
> +- "!include public__cris_import_log.yaml"
idk why this moved :shrug:

2024-08-20 01:06 UTC, mddilley approved these changes
Tested locally, and the new field looks great in the UI. The values that I see in the crash page match up with what I'm seeing in `crash_injury_metrics_view` too. 🚢 😎

2024-08-20 01:06 UTC, mddilley commented on atd-vze/src/views/Crashes/crashDataMap.js
Took me a second to understand the difference between these two fields but the DB showed me the way ✨

2024-08-20 13:01 UTC, johnclary requested changes
Looks great! just the smallest possible change needed

2024-08-20 13:01 UTC, johnclary commented on atd-vze/src/views/Crashes/crashDataMap.js
> +          label: " Total Est. Comprehensive Cost",
Looks like his leading whitespace space can be removed

2024-08-20 15:09 UTC, johnclary approved these changes
i fixed the whitespace and am gonna merge! 🙏

2024-08-20 15:09 UTC, merged