Move victim name to the right of people table
cityofaustin/atd-vz-data pull request #1532
Opened 2024-08-27 19:20 UTC by roseeichelmann

## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/18816

## Testing
**URL to test:** 
Netlify

**Steps to test:**
1. For people with fatal injuries, see that the victim name column is now to the far right of the table. Check this for primary and non primary people.

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-08-28 16:06 UTC, johnclary requested changes
this looks good, but there is a little horizontal scrollbar that seems to be visible at every page width. can you squash whatever is tripping that?

<img width="606" alt="Screenshot 2024-08-28 at 12 04 33 PM" src="https://github.com/user-attachments/assets/282797d9-c4ed-4953-91c6-26708b99bf00">

2024-08-30 13:35 UTC, johnclary commented on atd-vze/src/views/Crashes/VictimNameField.js
> -        <Form>
can we keep the form element here, too? just as a best practice.

2024-08-30 13:35 UTC, johnclary approved these changes
horizontal scrollbar is gone! would you mind adding the `<form>` back in? then ship it! 🚢 🚢 🚢 🚢

2024-08-30 13:47 UTC, chiaberry approved these changes
✅

2024-08-30 16:55 UTC, merged